# Generated by Django 5.2.17 on 2026-09-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantUsageBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_key_hash', models.CharField(db_index=True, max_length=64)),
                ('bucket_date', models.DateField(db_index=True)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('blocked_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-bucket_date',),
                'constraints': [models.UniqueConstraint(fields=('anonymous_key_hash', 'bucket_date'), name='assistant_usage_bucket_key_date_unique')],
            },
        ),
    ]
