# Generated by Django 5.1.3 on 2026-04-15 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('target_role', models.CharField(blank=True, max_length=150)),
                ('custom_summary', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('ats_tags', models.CharField(blank=True, max_length=500)),
                ('include_education', models.ManyToManyField(blank=True, to='portfolio.education')),
                ('include_experiences', models.ManyToManyField(blank=True, to='portfolio.experience')),
                ('include_projects', models.ManyToManyField(blank=True, to='portfolio.project')),
                ('include_skills', models.ManyToManyField(blank=True, to='portfolio.skill')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='ResumeExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('json', 'JSON'), ('html', 'HTML')], max_length=8)),
                ('file', models.FileField(blank=True, null=True, upload_to='resume_exports/')),
                ('download_count_snapshot', models.PositiveIntegerField(default=0)),
                ('resume_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='resume_builder.resumeversion')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
