# Generated by Django 5.2.17 on 2026-09-14 20:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def populate_version_uuids(apps, schema_editor):
    resume_version_model = apps.get_model("resume_builder", "ResumeVersion")
    for resume_version in resume_version_model.objects.filter(version_uuid__isnull=True).iterator():
        resume_version.version_uuid = uuid.uuid4()
        resume_version.save(update_fields=("version_uuid",))


def restore_legacy_statuses(apps, schema_editor):
    resume_version_model = apps.get_model("resume_builder", "ResumeVersion")
    resume_version_model.objects.filter(status="approved").update(status="draft")
    resume_version_model.objects.filter(status="archived", published_at__isnull=False).update(status="published")
    resume_version_model.objects.filter(status="archived", published_at__isnull=True).update(status="draft")


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_certification'),
        ('resume_builder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplicationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('organization', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('job_url', models.URLField(blank=True)),
                ('job_description_snapshot', models.TextField(blank=True)),
                ('job_description_hash', models.CharField(blank=True, max_length=64)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('saved', 'Saved'), ('applied', 'Applied'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=12)),
                ('submitted_format', models.CharField(blank=True, choices=[('pdf', 'PDF'), ('docx', 'DOCX')], max_length=4)),
                ('submitted_artifact_sha256', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='resumeexport',
            name='binary_content',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeexport',
            name='byte_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumeexport',
            name='content_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='resumeexport',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeexport',
            name='generation_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resumeexport',
            name='sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='resumeexport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_versions_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_versions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_versions_published', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='resume_content',
            field=models.JSONField(blank=True, default=dict, help_text='Résumé-formatted wording referencing source claim IDs. It is not read from live portfolio content after approval.'),
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='resume_type',
            field=models.CharField(choices=[('master', 'Master'), ('tailored', 'Tailored')], default='master', max_length=8),
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='snapshot_schema_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='source_facts',
            field=models.JSONField(blank=True, default=dict, help_text='Canonical verified facts and provenance. It is not read from live portfolio content after approval.'),
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='source_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Canonical SHA-256 of the source snapshot, populated by a later workflow.', max_length=64),
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='target_organization',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='version_uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(
            populate_version_uuids,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='resumeversion',
            name='version_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='resumeexport',
            name='format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('json', 'JSON'), ('html', 'HTML'), ('docx', 'DOCX')], max_length=8),
        ),
        migrations.AlterField(
            model_name='resumeversion',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=12),
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            reverse_code=restore_legacy_statuses,
        ),
        migrations.AddConstraint(
            model_name='resumeexport',
            constraint=models.UniqueConstraint(fields=('resume_version', 'format'), name='resume_export_version_format_unique'),
        ),
        migrations.AddConstraint(
            model_name='resumeversion',
            constraint=models.UniqueConstraint(condition=models.Q(('resume_type', 'master'), ('status', 'published')), fields=('resume_type',), name='resume_one_published_master'),
        ),
        migrations.AddConstraint(
            model_name='resumeversion',
            constraint=models.CheckConstraint(condition=models.Q(('is_default', False), models.Q(('resume_type', 'master'), ('status', 'published')), _connector='OR'), name='resume_default_published_master'),
        ),
        migrations.AddConstraint(
            model_name='resumeversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resume_type', 'master'), ('status', 'published'), _negated=True), ('is_default', True), _connector='OR'), name='resume_published_master_default'),
        ),
        migrations.AddConstraint(
            model_name='resumeversion',
            constraint=models.CheckConstraint(condition=models.Q(('resume_type', 'master'), models.Q(('status__in', ('draft', 'approved', 'archived')), ('is_default', False)), _connector='OR'), name='resume_tailored_not_published_default'),
        ),
        migrations.AddField(
            model_name='jobapplicationrecord',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_application_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplicationrecord',
            name='resume_export',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='resume_builder.resumeexport'),
        ),
        migrations.AddField(
            model_name='jobapplicationrecord',
            name='resume_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='resume_builder.resumeversion'),
        ),
    ]
