# Generated by Django 5.2.17 on 2026-09-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_certification'),
        ('resume_builder', '0002_jobapplicationrecord_resumeexport_binary_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeversion',
            name='include_certifications',
            field=models.ManyToManyField(blank=True, related_name='resume_versions', to='portfolio.certification'),
        ),
    ]
