# Generated by Django 5.2.17 on 2026-09-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0003_resumeversion_include_certifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeversion',
            name='resume_content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
