# Generated by Django 5.2.17 on 2026-09-14 21:58

import django.db.models.deletion
import django.core.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0004_resumeversion_resume_content_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('assessment_type', models.CharField(choices=[('readiness', 'Readiness'), ('job_match', 'Job match')], max_length=16)),
                ('score', models.PositiveSmallIntegerField()),
                ('ruleset_version', models.CharField(max_length=32)),
                ('resume_content_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Must be a lowercase SHA-256 hexadecimal hash.')])),
                ('source_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Must be a lowercase SHA-256 hexadecimal hash.')])),
                ('job_description_hash', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Must be a lowercase SHA-256 hexadecimal hash.')])),
                ('report', models.JSONField(blank=True, default=dict)),
                ('critical_blockers', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_assessments_created', to=settings.AUTH_USER_MODEL)),
                ('job_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='resume_builder.jobapplicationrecord')),
                ('resume_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='resume_builder.resumeversion')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 100)), name='assessment_score_0_100'), models.CheckConstraint(condition=models.Q(models.Q(('assessment_type', 'readiness'), ('job_application__isnull', True), ('job_description_hash', '')), models.Q(('assessment_type', 'job_match'), ('job_application__isnull', False), ('job_description_hash__regex', '^[0-9a-f]{64}$')), _connector='OR'), name='assessment_type_requirements'), models.UniqueConstraint(fields=('resume_version', 'assessment_type', 'ruleset_version', 'resume_content_hash', 'job_description_hash'), name='assessment_exact_duplicate')],
            },
        ),
    ]
