# Generated by Django 5.2.17 on 2026-09-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_contact_ops_01_tracking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='business_problem',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='consent_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='discovery_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='existing_assets',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='expected_outcome',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='optional_features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='organization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='preferred_contact_method',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='project_stage',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='project_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='required_features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='source',
            field=models.CharField(choices=[('contact_form', 'Contact form'), ('project_discovery', 'Project discovery'), ('assistant', 'Assistant')], default='contact_form', max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='target_users',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='technical_preferences',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
