# Generated by Django 5.1.3 on 2026-04-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(default='Shahriyar Portfolio', max_length=120)),
                ('owner_name', models.CharField(default='Shahriyar Khan', max_length=120)),
                ('public_email', models.EmailField(blank=True, max_length=254)),
                ('public_phone', models.CharField(blank=True, max_length=40)),
                ('public_location', models.CharField(blank=True, max_length=120)),
                ('notification_email', models.EmailField(blank=True, max_length=254)),
                ('hero_title', models.CharField(blank=True, max_length=255)),
                ('hero_subtitle', models.CharField(blank=True, max_length=500)),
                ('default_seo_title', models.CharField(blank=True, max_length=255)),
                ('default_seo_description', models.TextField(blank=True)),
                ('default_keywords', models.CharField(blank=True, max_length=500)),
                ('footer_text', models.CharField(blank=True, max_length=255)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
