# Generated by Django 5.1.3 on 2026-04-15 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('page_visit', 'Page Visit'), ('project_view', 'Project View'), ('project_click', 'Project Click'), ('contact_submit', 'Contact Submit'), ('service_request_submit', 'Service Request Submit'), ('resume_download', 'Resume Download')], max_length=30)),
                ('page_path', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session_id', models.CharField(blank=True, max_length=128)),
                ('ip_hash', models.CharField(blank=True, max_length=128)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='portfolio.project')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='analytics_a_event_t_f6cbfd_idx'), models.Index(fields=['page_path'], name='analytics_a_page_pa_a761ec_idx')],
            },
        ),
    ]
